name: unpub_web
description: A web app that uses AngularDart Components
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1
  angular_router: ^3.0.1
  http: ^1.2.1
  markdown: ^7.2.2
  unpub_api:
    path: ../unpub/lib/unpub_api
dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.5
