name: unpub_auth
description: An auth tool for unpub.
version: 0.1.0+3
homepage: https://github.com/bytedance/unpub

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  unpub_auth:

dependencies:
  collection: ^1.18.0
  path: ^1.9.0
  http: ^1.2.1
  shelf: ^1.4.1
  http_multi_server: ^3.2.1
  oauth2: ^2.0.2
  args: ^2.5.0
  console: ^4.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
