name: unpub_aws
description: A collection of modules to use for deploying unpub into AWS infrastructure.
version: 0.1.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  unpub: ^2.1.0
  minio: ^3.5.0
  http: ^0.13.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
  chunked_stream: ^1.4.2
  mockito: ^5.4.4
  build_runner: ^2.4.11
  path: ^1.9.0
  json_annotation: ^4.9.0
# dependency_overrides:
#   unpub:
#     path: ../unpub
