name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 2.0.1-dev.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=3.0.0 <4.0.0"
executables:
  unpub: unpub
dependencies:
  args: ^2.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http_parser: ^4.0.2
  http: ^1.2.1
  archive: ^3.6.1
  logging: ^1.2.0
  meta: ^1.15.0
  googleapis: ^13.1.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.3
  mime: ^1.0.5
  intl: ^0.19.0
  path: ^1.9.0
  collection: ^1.18.0
  shelf_cors_headers: ^0.1.5
dev_dependencies:
  test: ^1.25.7
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  shelf_router_generator: ^1.1.0
  chunked_stream: ^1.4.2
